[world]
kind = "WorldContract"
class_hash = "0x3715f072aa1c07be724249fcda8b0322687f6c5c585eebc4402d162649c707c"
original_class_hash = "0x3715f072aa1c07be724249fcda8b0322687f6c5c585eebc4402d162649c707c"
abi = "manifests/sepolia/deployment/abis/dojo-world.json"
address = "0x5903f818fe01b1f48f3a234a2b186e92cc2825c32a9b62c4453f6989ff11709"
transaction_hash = "0x18a618b5f05a1aabd2a73365409a43caf9951c0d5dee4eaea27664272d4fddb"
seed = "zIdle"
manifest_name = "dojo-world"

[world.metadata]
profile_name = "sepolia"
rpc_url = "https://starknet-sepolia.public.blastapi.io/rpc/v0_7"

[base]
kind = "Class"
class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
original_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/sepolia/deployment/abis/dojo-base.json"
tag = "dojo-base"
manifest_name = "dojo-base"

[[contracts]]
kind = "DojoContract"
class_hash = "0x12cee1ace375000519728f8eb72b8a2428a025aa4571217c67d526235269328"
original_class_hash = "0x12cee1ace375000519728f8eb72b8a2428a025aa4571217c67d526235269328"
base_class_hash = "0x0"
abi = "manifests/sepolia/deployment/abis/contracts/zidle4-character-7fa84d42.json"
reads = []
writes = [
    "zidle4-Miner",
    "zidle4-Player",
]
init_calldata = []
tag = "zidle4-character"
systems = ["create"]
manifest_name = "zidle4-character-7fa84d42"

[[contracts]]
kind = "DojoContract"
class_hash = "0x71340c826bd65381c14e54702167c42286b6d340456f80f99d5984825b49eab"
original_class_hash = "0x71340c826bd65381c14e54702167c42286b6d340456f80f99d5984825b49eab"
base_class_hash = "0x0"
abi = "manifests/sepolia/deployment/abis/contracts/zidle4-character_minter-7301837c.json"
reads = []
writes = ["zidle4-TokenConfig"]
init_calldata = [
    "$contract_address:zidle4-character_token",
    "10000",
    "0",
    "100",
    "0",
    "1",
]
tag = "zidle4-character_minter"
systems = ["set_open"]
manifest_name = "zidle4-character_minter-7301837c"

[[contracts]]
kind = "DojoContract"
class_hash = "0x909f421741a4c03766948125f3730a3e279b63ffce2f079d85f3c40a3b8a24"
original_class_hash = "0x909f421741a4c03766948125f3730a3e279b63ffce2f079d85f3c40a3b8a24"
base_class_hash = "0x0"
abi = "manifests/sepolia/deployment/abis/contracts/zidle4-character_token-6f0dd2c7.json"
reads = []
writes = [
    "zidle_token4-SRC5Model",
    "zidle_token4-InitializableModel",
    "zidle_token4-ERC721OwnerModel",
    "zidle_token4-ERC721BalanceModel",
    "zidle_token4-ERC721MetaModel",
    "zidle_token4-ERC721EnumerableIndexModel",
    "zidle_token4-ERC721EnumerableOwnerIndexModel",
    "zidle_token4-ERC721EnumerableOwnerTokenModel",
    "zidle_token4-ERC721EnumerableTokenModel",
    "zidle_token4-ERC721EnumerableTotalModel",
    "zidle_token4-ERC721TokenApprovalModel",
    "zidle_token4-ERC721OperatorApprovalModel",
    "zidle4-ERC721WalletModel",
]
init_calldata = []
tag = "zidle4-character_token"
systems = [
    "mint",
    "burn",
]
manifest_name = "zidle4-character_token-6f0dd2c7"

[[contracts]]
kind = "DojoContract"
class_hash = "0x2dda6c8c5bfd38805bd27974a9bdd78d163de2096601b027700a7f8d81a3ad7"
original_class_hash = "0x2dda6c8c5bfd38805bd27974a9bdd78d163de2096601b027700a7f8d81a3ad7"
base_class_hash = "0x0"
abi = "manifests/sepolia/deployment/abis/contracts/zidle4-gold_minter-764574f2.json"
reads = []
writes = ["zidle4-TokenConfig"]
init_calldata = [
    "$contract_address:zidle4-gold_token",
    "1000000000000000",
    "0",
    "1000000000000000",
    "0",
    "1",
]
tag = "zidle4-gold_minter"
systems = [
    "mint",
    "set_open",
]
manifest_name = "zidle4-gold_minter-764574f2"

[[contracts]]
kind = "DojoContract"
class_hash = "0x7bbdb9c2b3ea83151c9ece466203fea13413a5d82100974c12c336fccaf3499"
original_class_hash = "0x7bbdb9c2b3ea83151c9ece466203fea13413a5d82100974c12c336fccaf3499"
base_class_hash = "0x0"
abi = "manifests/sepolia/deployment/abis/contracts/zidle4-gold_token-7e378aaa.json"
reads = []
writes = [
    "zidle_token4-SRC5Model",
    "zidle_token4-InitializableModel",
    "zidle_token4-ERC20BalanceModel",
    "zidle_token4-ERC20MetadataModel",
    "zidle_token4-ERC20AllowanceModel",
]
init_calldata = []
tag = "zidle4-gold_token"
systems = [
    "mint",
    "burn",
]
manifest_name = "zidle4-gold_token-7e378aaa"

[[contracts]]
kind = "DojoContract"
class_hash = "0x2bbe2cf699d1eb83d4972988fa7294d95b18add1e2ffb185a918844913d64a0"
original_class_hash = "0x2bbe2cf699d1eb83d4972988fa7294d95b18add1e2ffb185a918844913d64a0"
base_class_hash = "0x0"
abi = "manifests/sepolia/deployment/abis/contracts/zidle4-resources-601cc872.json"
reads = []
writes = [
    "zidle4-Char",
    "zidle4-Player",
    "zidle4-Miner",
    "zidle4-TokenConfig",
]
init_calldata = []
tag = "zidle4-resources"
systems = [
    "mine",
    "harvest",
    "sell",
]
manifest_name = "zidle4-resources-601cc872"

[[models]]
kind = "DojoModel"
class_hash = "0xf83053119a31807663f48f62f8030c27a1f694fbac3b6b0a7a2b08c8950576"
original_class_hash = "0xf83053119a31807663f48f62f8030c27a1f694fbac3b6b0a7a2b08c8950576"
abi = "manifests/sepolia/deployment/abis/models/zidle4-Char-278f2c1c.json"
tag = "zidle4-Char"
qualified_path = "zidle::models::char::char"
manifest_name = "zidle4-Char-278f2c1c"

[[models.members]]
name = "id"
type = "felt252"
key = true

[[models.members]]
name = "token_id"
type = "u128"
key = true

[[models.members]]
name = "name"
type = "felt252"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x1b3c94e13b6afd01ae6cfa4029ad71bcf71a1e4984da5e000e5db7cdad4aeac"
original_class_hash = "0x1b3c94e13b6afd01ae6cfa4029ad71bcf71a1e4984da5e000e5db7cdad4aeac"
abi = "manifests/sepolia/deployment/abis/models/zidle4-ERC721WalletModel-441b342f.json"
tag = "zidle4-ERC721WalletModel"
qualified_path = "zidle::components::erc721::erc721_wallet::erc_721_wallet_model"
manifest_name = "zidle4-ERC721WalletModel-441b342f"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "token_id"
type = "u128"
key = true

[[models.members]]
name = "address"
type = "ContractAddress"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x40848012b8c01edf63fc9752ec21c789c118a4f68eeabab1b9c44f0ba6cea0"
original_class_hash = "0x40848012b8c01edf63fc9752ec21c789c118a4f68eeabab1b9c44f0ba6cea0"
abi = "manifests/sepolia/deployment/abis/models/zidle4-Miner-1d71b5d0.json"
tag = "zidle4-Miner"
qualified_path = "zidle::models::miner::miner"
manifest_name = "zidle4-Miner-1d71b5d0"

[[models.members]]
name = "token_id"
type = "u128"
key = true

[[models.members]]
name = "resource_type"
type = "u8"
key = true

[[models.members]]
name = "xp"
type = "u64"
key = false

[[models.members]]
name = "timestamp"
type = "u64"
key = false

[[models.members]]
name = "subresource_type"
type = "u8"
key = false

[[models.members]]
name = "rcs_1"
type = "u64"
key = false

[[models.members]]
name = "rcs_2"
type = "u64"
key = false

[[models.members]]
name = "rcs_3"
type = "u64"
key = false

[[models.members]]
name = "rcs_4"
type = "u64"
key = false

[[models.members]]
name = "rcs_5"
type = "u64"
key = false

[[models.members]]
name = "rcs_6"
type = "u64"
key = false

[[models.members]]
name = "rcs_7"
type = "u64"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x1e24ff1e74a9993f6db8198caa27700c0926758f48443ea1aff170f6e390492"
original_class_hash = "0x1e24ff1e74a9993f6db8198caa27700c0926758f48443ea1aff170f6e390492"
abi = "manifests/sepolia/deployment/abis/models/zidle4-Player-3c7da8a6.json"
tag = "zidle4-Player"
qualified_path = "zidle::models::player::player"
manifest_name = "zidle4-Player-3c7da8a6"

[[models.members]]
name = "token_id"
type = "felt252"
key = true

[[models.members]]
name = "name"
type = "felt252"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x14562e8e15e1d82680bbbbdfdc0f154027dfec666e1431b07a23e48190f721c"
original_class_hash = "0x14562e8e15e1d82680bbbbdfdc0f154027dfec666e1431b07a23e48190f721c"
abi = "manifests/sepolia/deployment/abis/models/zidle4-TokenConfig-23178dee.json"
tag = "zidle4-TokenConfig"
qualified_path = "zidle::models::token_config::token_config"
manifest_name = "zidle4-TokenConfig-23178dee"

[[models.members]]
name = "token_address"
type = "ContractAddress"
key = true

[[models.members]]
name = "max_supply"
type = "u256"
key = false

[[models.members]]
name = "minted_count"
type = "u256"
key = false

[[models.members]]
name = "max_per_wallet"
type = "u256"
key = false

[[models.members]]
name = "is_open"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x4a261cc27abca90c82dfe0d4c5af19c4cd3d14ce3279d7cff7cd24ee20b238a"
original_class_hash = "0x4a261cc27abca90c82dfe0d4c5af19c4cd3d14ce3279d7cff7cd24ee20b238a"
abi = "manifests/sepolia/deployment/abis/models/zidle_token4-ERC20AllowanceModel-13d92df7.json"
tag = "zidle_token4-ERC20AllowanceModel"
qualified_path = "origami_token::components::token::erc20::erc20_allowance::erc_20_allowance_model"
manifest_name = "zidle_token4-ERC20AllowanceModel-13d92df7"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "owner"
type = "ContractAddress"
key = true

[[models.members]]
name = "spender"
type = "ContractAddress"
key = true

[[models.members]]
name = "amount"
type = "u256"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x6e775153446eebf73db1137b9e0db621eb3eac4f411ec6aee8eeb593acec667"
original_class_hash = "0x6e775153446eebf73db1137b9e0db621eb3eac4f411ec6aee8eeb593acec667"
abi = "manifests/sepolia/deployment/abis/models/zidle_token4-ERC20BalanceModel-7f8642a9.json"
tag = "zidle_token4-ERC20BalanceModel"
qualified_path = "origami_token::components::token::erc20::erc20_balance::erc_20_balance_model"
manifest_name = "zidle_token4-ERC20BalanceModel-7f8642a9"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "account"
type = "ContractAddress"
key = true

[[models.members]]
name = "amount"
type = "u256"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x49571dd250b65acabbf7acd49b0ae53653562c447781ffd82453daf4a6e62f2"
original_class_hash = "0x49571dd250b65acabbf7acd49b0ae53653562c447781ffd82453daf4a6e62f2"
abi = "manifests/sepolia/deployment/abis/models/zidle_token4-ERC20MetadataModel-6c06004d.json"
tag = "zidle_token4-ERC20MetadataModel"
qualified_path = "origami_token::components::token::erc20::erc20_metadata::erc_20_metadata_model"
manifest_name = "zidle_token4-ERC20MetadataModel-6c06004d"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "name"
type = "ByteArray"
key = false

[[models.members]]
name = "symbol"
type = "ByteArray"
key = false

[[models.members]]
name = "decimals"
type = "u8"
key = false

[[models.members]]
name = "total_supply"
type = "u256"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x2e5c3283ab5e7ed6dd67b0ea8951047efd78197786aa9c0f758ec9665295ae"
original_class_hash = "0x2e5c3283ab5e7ed6dd67b0ea8951047efd78197786aa9c0f758ec9665295ae"
abi = "manifests/sepolia/deployment/abis/models/zidle_token4-ERC721BalanceModel-385579cc.json"
tag = "zidle_token4-ERC721BalanceModel"
qualified_path = "origami_token::components::token::erc721::erc721_balance::erc_721_balance_model"
manifest_name = "zidle_token4-ERC721BalanceModel-385579cc"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "account"
type = "ContractAddress"
key = true

[[models.members]]
name = "amount"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x37109b99618162707ab70638d2343db8d63de8753524a55fd610fb7e4350afa"
original_class_hash = "0x37109b99618162707ab70638d2343db8d63de8753524a55fd610fb7e4350afa"
abi = "manifests/sepolia/deployment/abis/models/zidle_token4-ERC721EnumerableIndexModel-52889cb7.json"
tag = "zidle_token4-ERC721EnumerableIndexModel"
qualified_path = "origami_token::components::token::erc721::erc721_enumerable::erc_721_enumerable_index_model"
manifest_name = "zidle_token4-ERC721EnumerableIndexModel-52889cb7"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "index"
type = "u128"
key = true

[[models.members]]
name = "token_id"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x5c4ab582e8cd1c433129f66822622cfb2fb358467191c8a575eb860c9fafb32"
original_class_hash = "0x5c4ab582e8cd1c433129f66822622cfb2fb358467191c8a575eb860c9fafb32"
abi = "manifests/sepolia/deployment/abis/models/zidle_token4-ERC721EnumerableOwnerIndexModel-72573315.json"
tag = "zidle_token4-ERC721EnumerableOwnerIndexModel"
qualified_path = "origami_token::components::token::erc721::erc721_enumerable::erc_721_enumerable_owner_index_model"
manifest_name = "zidle_token4-ERC721EnumerableOwnerIndexModel-72573315"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "owner"
type = "ContractAddress"
key = true

[[models.members]]
name = "index"
type = "u128"
key = true

[[models.members]]
name = "token_id"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x1b8cde8a90e509700ac1dc916bd9f7d28e697eac8ebbba9348cd14b8c742ce9"
original_class_hash = "0x1b8cde8a90e509700ac1dc916bd9f7d28e697eac8ebbba9348cd14b8c742ce9"
abi = "manifests/sepolia/deployment/abis/models/zidle_token4-ERC721EnumerableOwnerTokenModel-182820f2.json"
tag = "zidle_token4-ERC721EnumerableOwnerTokenModel"
qualified_path = "origami_token::components::token::erc721::erc721_enumerable::erc_721_enumerable_owner_token_model"
manifest_name = "zidle_token4-ERC721EnumerableOwnerTokenModel-182820f2"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "owner"
type = "ContractAddress"
key = true

[[models.members]]
name = "token_id"
type = "u128"
key = true

[[models.members]]
name = "index"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x7bdca01db25c37bb98dcc236056ef6a40004a3dc6987210eda0dc2d6da48d45"
original_class_hash = "0x7bdca01db25c37bb98dcc236056ef6a40004a3dc6987210eda0dc2d6da48d45"
abi = "manifests/sepolia/deployment/abis/models/zidle_token4-ERC721EnumerableTokenModel-4d0b0c92.json"
tag = "zidle_token4-ERC721EnumerableTokenModel"
qualified_path = "origami_token::components::token::erc721::erc721_enumerable::erc_721_enumerable_token_model"
manifest_name = "zidle_token4-ERC721EnumerableTokenModel-4d0b0c92"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "token_id"
type = "u128"
key = true

[[models.members]]
name = "index"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x4d0c26fc751866987e49b4c83f66b28cc64ef0a31d49893b1451cab2983fc60"
original_class_hash = "0x4d0c26fc751866987e49b4c83f66b28cc64ef0a31d49893b1451cab2983fc60"
abi = "manifests/sepolia/deployment/abis/models/zidle_token4-ERC721EnumerableTotalModel-252b24ce.json"
tag = "zidle_token4-ERC721EnumerableTotalModel"
qualified_path = "origami_token::components::token::erc721::erc721_enumerable::erc_721_enumerable_total_model"
manifest_name = "zidle_token4-ERC721EnumerableTotalModel-252b24ce"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "total_supply"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x2fe8f3cb5b65177042742bc4a53e49034e8523c32dc4939ef4c7ff04fc40eb4"
original_class_hash = "0x2fe8f3cb5b65177042742bc4a53e49034e8523c32dc4939ef4c7ff04fc40eb4"
abi = "manifests/sepolia/deployment/abis/models/zidle_token4-ERC721MetaModel-42f176a3.json"
tag = "zidle_token4-ERC721MetaModel"
qualified_path = "origami_token::components::token::erc721::erc721_metadata::erc_721_meta_model"
manifest_name = "zidle_token4-ERC721MetaModel-42f176a3"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "name"
type = "ByteArray"
key = false

[[models.members]]
name = "symbol"
type = "ByteArray"
key = false

[[models.members]]
name = "base_uri"
type = "ByteArray"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x6014eabd7f530279e07903c37ce7c6ba1a51be2d14b00e08b1fd31742103642"
original_class_hash = "0x6014eabd7f530279e07903c37ce7c6ba1a51be2d14b00e08b1fd31742103642"
abi = "manifests/sepolia/deployment/abis/models/zidle_token4-ERC721OperatorApprovalModel-88c35d2c.json"
tag = "zidle_token4-ERC721OperatorApprovalModel"
qualified_path = "origami_token::components::token::erc721::erc721_approval::erc_721_operator_approval_model"
manifest_name = "zidle_token4-ERC721OperatorApprovalModel-88c35d2c"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "owner"
type = "ContractAddress"
key = true

[[models.members]]
name = "operator"
type = "ContractAddress"
key = true

[[models.members]]
name = "approved"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x948f700ad378350f48fac0a13c314333cd904375a323e76c5b8a8e236d49b2"
original_class_hash = "0x948f700ad378350f48fac0a13c314333cd904375a323e76c5b8a8e236d49b2"
abi = "manifests/sepolia/deployment/abis/models/zidle_token4-ERC721OwnerModel-7201103c.json"
tag = "zidle_token4-ERC721OwnerModel"
qualified_path = "origami_token::components::token::erc721::erc721_owner::erc_721_owner_model"
manifest_name = "zidle_token4-ERC721OwnerModel-7201103c"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "token_id"
type = "u128"
key = true

[[models.members]]
name = "address"
type = "ContractAddress"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x60b20f282ddc28f8626468791deed210917631ff399b7da50ae4c1460f6f87f"
original_class_hash = "0x60b20f282ddc28f8626468791deed210917631ff399b7da50ae4c1460f6f87f"
abi = "manifests/sepolia/deployment/abis/models/zidle_token4-ERC721TokenApprovalModel-30ced592.json"
tag = "zidle_token4-ERC721TokenApprovalModel"
qualified_path = "origami_token::components::token::erc721::erc721_approval::erc_721_token_approval_model"
manifest_name = "zidle_token4-ERC721TokenApprovalModel-30ced592"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "token_id"
type = "u128"
key = true

[[models.members]]
name = "address"
type = "ContractAddress"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x7148c780747dff5930d66eb3df4cd8a900fb8b53a50a7f381f815e9840c79a1"
original_class_hash = "0x7148c780747dff5930d66eb3df4cd8a900fb8b53a50a7f381f815e9840c79a1"
abi = "manifests/sepolia/deployment/abis/models/zidle_token4-InitializableModel-3b8b43fd.json"
tag = "zidle_token4-InitializableModel"
qualified_path = "origami_token::components::security::initializable::initializable_model"
manifest_name = "zidle_token4-InitializableModel-3b8b43fd"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "initialized"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x557f688ac8ab214170486efea990d316d56e2ac6e549573e6a1384b356dfb73"
original_class_hash = "0x557f688ac8ab214170486efea990d316d56e2ac6e549573e6a1384b356dfb73"
abi = "manifests/sepolia/deployment/abis/models/zidle_token4-SRC5Model-2e7dd8ae.json"
tag = "zidle_token4-SRC5Model"
qualified_path = "origami_token::components::introspection::src5::src_5_model"
manifest_name = "zidle_token4-SRC5Model-2e7dd8ae"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "interface_id"
type = "felt252"
key = true

[[models.members]]
name = "supports"
type = "bool"
key = false
