tag = "zidle-gold_minter"
writes = [
  "zidle-TokenConfig",
]
init_calldata = [
  "$contract_address:zidle-gold_token",
  "1000000000000000",  # max supply
  "1000000000000000",  # max per wallet
  "1",      # is_open
]
