// Generated by dojo-bindgen on Fri, 24 Jan 2025 09:26:12 +0000. Do not modify this file manually.
import { Account } from 'starknet';
import {
  Clause,
  Client,
  ModelClause,
  createClient,
  valueToToriiValueAndOperator,
} from '@dojoengine/torii-client';
import {
  LOCAL_KATANA,
  LOCAL_RELAY,
  LOCAL_TORII,
  createManifestFromJson,
} from '@dojoengine/core';

// Type definition for `dojo::meta::layout::FieldLayout` struct
export interface FieldLayout {
  selector: string;
  layout: Layout;
}

// Type definition for `dojo::meta::introspect::Enum` struct
export interface Enum {
  name: string;
  attrs: string[];
  children: [string, Ty][];
}

// Type definition for `zidle::models::player::PlayerValue` struct
export interface PlayerValue {
  name: string;
}

// Type definition for `dojo::model::definition::ModelDef` struct
export interface ModelDef {
  name: string;
  layout: Layout;
  schema: Struct;
  packed_size: Option<number>;
  unpacked_size: Option<number>;
}

// Type definition for `dojo::meta::introspect::Member` struct
export interface Member {
  name: string;
  attrs: string[];
  ty: Ty;
}

// Type definition for `dojo::meta::introspect::Struct` struct
export interface Struct {
  name: string;
  attrs: string[];
  children: Member[];
}

// Type definition for `zidle::events::index::Mine` struct
export interface Mine {
  token_id: string;
  rcs_type: number;
  rcs_sub_type: number;
}

// Type definition for `zidle::events::index::Harvest` struct
export interface Harvest {
  token_id: string;
  rcs_type: number;
  rcs_sub_type: number;
  amount: number;
  xp: number;
}

// Type definition for `zidle::models::player::Player` struct
export interface Player {
  token_id: string;
  name: string;
}

// Type definition for `core::byte_array::ByteArray` struct
export interface ByteArray {
  data: string[];
  pending_word: string;
  pending_word_len: number;
}

// Type definition for `dojo::meta::introspect::Ty` enum
type Ty =
  | { type: 'Primitive'; data: string }
  | { type: 'Struct'; data: Struct }
  | { type: 'Enum'; data: Enum }
  | { type: 'Tuple'; data: Ty[] }
  | { type: 'Array'; data: Ty[] }
  | { type: 'ByteArray' };
// Type definition for `dojo::meta::layout::Layout` enum
type Layout =
  | { type: 'Fixed'; data: number[] }
  | { type: 'Struct'; data: FieldLayout[] }
  | { type: 'Tuple'; data: Layout[] }
  | { type: 'Array'; data: Layout[] }
  | { type: 'ByteArray' }
  | { type: 'Enum'; data: FieldLayout[] };
// Type definition for `core::option::Option::<core::integer::u32>` enum
type Option<A> = { type: 'Some'; data: A } | { type: 'None' };

// Type definition for `zidle::models::char::CharValue` struct
export interface CharValue {
  name: string;
}

// Type definition for `zidle::models::char::Char` struct
export interface Char {
  id: string;
  token_id: bigint;
  name: string;
}

// Type definition for `core::integer::u256` struct
export interface U256 {
  low: bigint;
  high: bigint;
}

// Type definition for `zidle::models::token_config::TokenConfig` struct
export interface TokenConfig {
  token_address: string;
  max_supply: U256;
  minted_count: U256;
  max_per_wallet: U256;
  is_open: boolean;
}

// Type definition for `zidle::models::token_config::TokenConfigValue` struct
export interface TokenConfigValue {
  max_supply: U256;
  minted_count: U256;
  max_per_wallet: U256;
  is_open: boolean;
}

// Type definition for `zidle::models::admin::AdminValue` struct
export interface AdminValue {
  is_set: boolean;
}

// Type definition for `zidle::models::admin::Admin` struct
export interface Admin {
  id: string;
  is_set: boolean;
}

// Type definition for `zidle::models::settings::Settings` struct
export interface Settings {
  id: number;
  gold_erc20_address: string;
  character_erc721_address: string;
  is_set: boolean;
}

// Type definition for `zidle::models::settings::SettingsValue` struct
export interface SettingsValue {
  gold_erc20_address: string;
  character_erc721_address: string;
  is_set: boolean;
}

// Type definition for `zidle::models::miner::MinerValue` struct
export interface MinerValue {
  xp: bigint;
  timestamp: bigint;
  subresource_type: number;
  rcs_1: bigint;
  rcs_2: bigint;
  rcs_3: bigint;
  rcs_4: bigint;
  rcs_5: bigint;
  rcs_6: bigint;
  rcs_7: bigint;
}

// Type definition for `zidle::models::miner::Miner` struct
export interface Miner {
  token_id: bigint;
  resource_type: number;
  xp: bigint;
  timestamp: bigint;
  subresource_type: number;
  rcs_1: bigint;
  rcs_2: bigint;
  rcs_3: bigint;
  rcs_4: bigint;
  rcs_5: bigint;
  rcs_6: bigint;
  rcs_7: bigint;
}

class BaseCalls {
  contractAddress: string;
  account?: Account;

  constructor(contractAddress: string, account?: Account) {
    this.account = account;
    this.contractAddress = contractAddress;
  }

  async execute(entrypoint: string, calldata: any[] = []): Promise<void> {
    if (!this.account) {
      throw new Error('No account set to interact with dojo_starter');
    }

    await this.account.execute(
      {
        contractAddress: this.contractAddress,
        entrypoint,
        calldata,
      },
      undefined,
      {
        maxFee: 0,
      }
    );
  }
}

class GoldMinterCalls extends BaseCalls {
  constructor(contractAddress: string, account?: Account) {
    super(contractAddress, account);
  }

  async upgrade(new_class_hash: string): Promise<void> {
    try {
      await this.execute('upgrade', [new_class_hash]);
    } catch (error) {
      console.error('Error executing upgrade:', error);
      throw error;
    }
  }

  async dojoName(): Promise<void> {
    try {
      await this.execute('dojo_name', []);
    } catch (error) {
      console.error('Error executing dojoName:', error);
      throw error;
    }
  }

  async worldDispatcher(): Promise<void> {
    try {
      await this.execute('world_dispatcher', []);
    } catch (error) {
      console.error('Error executing worldDispatcher:', error);
      throw error;
    }
  }

  async mint(
    to: string,
    amount: U256,
    token_contract_address: string
  ): Promise<void> {
    try {
      await this.execute('mint', [
        to,
        props.amount.low,
        props.amount.high,
        token_contract_address,
      ]);
    } catch (error) {
      console.error('Error executing mint:', error);
      throw error;
    }
  }

  async canMint(to: string, token_contract_address: string): Promise<void> {
    try {
      await this.execute('can_mint', [to, token_contract_address]);
    } catch (error) {
      console.error('Error executing canMint:', error);
      throw error;
    }
  }

  async setOpen(
    token_contract_address: string,
    is_open: boolean
  ): Promise<void> {
    try {
      await this.execute('set_open', [token_contract_address, is_open]);
    } catch (error) {
      console.error('Error executing setOpen:', error);
      throw error;
    }
  }
}
class CharacterCalls extends BaseCalls {
  constructor(contractAddress: string, account?: Account) {
    super(contractAddress, account);
  }

  async upgrade(new_class_hash: string): Promise<void> {
    try {
      await this.execute('upgrade', [new_class_hash]);
    } catch (error) {
      console.error('Error executing upgrade:', error);
      throw error;
    }
  }

  async create(name: string): Promise<void> {
    try {
      await this.execute('create', [name]);
    } catch (error) {
      console.error('Error executing create:', error);
      throw error;
    }
  }

  async worldDispatcher(): Promise<void> {
    try {
      await this.execute('world_dispatcher', []);
    } catch (error) {
      console.error('Error executing worldDispatcher:', error);
      throw error;
    }
  }

  async dojoName(): Promise<void> {
    try {
      await this.execute('dojo_name', []);
    } catch (error) {
      console.error('Error executing dojoName:', error);
      throw error;
    }
  }
}
class SettingsCalls extends BaseCalls {
  constructor(contractAddress: string, account?: Account) {
    super(contractAddress, account);
  }

  async worldDispatcher(): Promise<void> {
    try {
      await this.execute('world_dispatcher', []);
    } catch (error) {
      console.error('Error executing worldDispatcher:', error);
      throw error;
    }
  }

  async updateGoldErc20Address(address: string): Promise<void> {
    try {
      await this.execute('update_gold_erc20_address', [address]);
    } catch (error) {
      console.error('Error executing updateGoldErc20Address:', error);
      throw error;
    }
  }

  async updateCharacterErc721Address(address: string): Promise<void> {
    try {
      await this.execute('update_character_erc721_address', [address]);
    } catch (error) {
      console.error('Error executing updateCharacterErc721Address:', error);
      throw error;
    }
  }

  async dojoName(): Promise<void> {
    try {
      await this.execute('dojo_name', []);
    } catch (error) {
      console.error('Error executing dojoName:', error);
      throw error;
    }
  }

  async upgrade(new_class_hash: string): Promise<void> {
    try {
      await this.execute('upgrade', [new_class_hash]);
    } catch (error) {
      console.error('Error executing upgrade:', error);
      throw error;
    }
  }
}
class ResourcesCalls extends BaseCalls {
  constructor(contractAddress: string, account?: Account) {
    super(contractAddress, account);
  }

  async mine(
    token_id: bigint,
    rcs_type: number,
    rcs_sub_type: number
  ): Promise<void> {
    try {
      await this.execute('mine', [token_id, rcs_type, rcs_sub_type]);
    } catch (error) {
      console.error('Error executing mine:', error);
      throw error;
    }
  }

  async harvest(token_id: bigint, rcs_type: number): Promise<void> {
    try {
      await this.execute('harvest', [token_id, rcs_type]);
    } catch (error) {
      console.error('Error executing harvest:', error);
      throw error;
    }
  }

  async sell(
    token_id: bigint,
    rcs_type: number,
    rcs_sub_type: number,
    amount: bigint
  ): Promise<void> {
    try {
      await this.execute('sell', [token_id, rcs_type, rcs_sub_type, amount]);
    } catch (error) {
      console.error('Error executing sell:', error);
      throw error;
    }
  }

  async dojoName(): Promise<void> {
    try {
      await this.execute('dojo_name', []);
    } catch (error) {
      console.error('Error executing dojoName:', error);
      throw error;
    }
  }

  async worldDispatcher(): Promise<void> {
    try {
      await this.execute('world_dispatcher', []);
    } catch (error) {
      console.error('Error executing worldDispatcher:', error);
      throw error;
    }
  }

  async upgrade(new_class_hash: string): Promise<void> {
    try {
      await this.execute('upgrade', [new_class_hash]);
    } catch (error) {
      console.error('Error executing upgrade:', error);
      throw error;
    }
  }
}
class CharacterMinterCalls extends BaseCalls {
  constructor(contractAddress: string, account?: Account) {
    super(contractAddress, account);
  }

  async upgrade(new_class_hash: string): Promise<void> {
    try {
      await this.execute('upgrade', [new_class_hash]);
    } catch (error) {
      console.error('Error executing upgrade:', error);
      throw error;
    }
  }

  async worldDispatcher(): Promise<void> {
    try {
      await this.execute('world_dispatcher', []);
    } catch (error) {
      console.error('Error executing worldDispatcher:', error);
      throw error;
    }
  }

  async dojoName(): Promise<void> {
    try {
      await this.execute('dojo_name', []);
    } catch (error) {
      console.error('Error executing dojoName:', error);
      throw error;
    }
  }

  async mint(to: string, token_contract_address: string): Promise<void> {
    try {
      await this.execute('mint', [to, token_contract_address]);
    } catch (error) {
      console.error('Error executing mint:', error);
      throw error;
    }
  }

  async canMint(to: string, token_contract_address: string): Promise<void> {
    try {
      await this.execute('can_mint', [to, token_contract_address]);
    } catch (error) {
      console.error('Error executing canMint:', error);
      throw error;
    }
  }

  async setOpen(
    token_contract_address: string,
    is_open: boolean
  ): Promise<void> {
    try {
      await this.execute('set_open', [token_contract_address, is_open]);
    } catch (error) {
      console.error('Error executing setOpen:', error);
      throw error;
    }
  }
}

type Query = Partial<{
  Player: ModelClause<Player>;
  Char: ModelClause<Char>;
  TokenConfig: ModelClause<TokenConfig>;
  Admin: ModelClause<Admin>;
  Settings: ModelClause<Settings>;
  Miner: ModelClause<Miner>;
}>;

type ResultMapping = {
  Player: Player;
  Char: Char;
  TokenConfig: TokenConfig;
  Admin: Admin;
  Settings: Settings;
  Miner: Miner;
};

type QueryResult<T extends Query> = {
  [K in keyof T]: K extends keyof ResultMapping ? ResultMapping[K] : never;
};

// Only supports a single model for now, since torii doesn't support multiple models
// And inside that single model, there's only support for a single query.
function convertQueryToToriiClause(query: Query): Clause | undefined {
  const [model, clause] = Object.entries(query)[0];

  if (Object.keys(clause).length === 0) {
    return undefined;
  }

  const clauses: Clause[] = Object.entries(clause).map(([key, value]) => {
    return {
      Member: {
        model,
        member: key,
        ...valueToToriiValueAndOperator(value),
      },
    } satisfies Clause;
  });

  return clauses[0];
}
type GeneralParams = {
  toriiUrl?: string;
  relayUrl?: string;
  account?: Account;
};

type InitialParams = GeneralParams &
  (
    | {
        rpcUrl?: string;
        worldAddress: string;
        goldMinterAddress: string;
        characterAddress: string;
        settingsAddress: string;
        resourcesAddress: string;
        characterMinterAddress: string;
      }
    | {
        manifest: any;
      }
  );

export class Zidle {
  rpcUrl: string;
  toriiUrl: string;
  toriiPromise: Promise<Client>;
  relayUrl: string;
  worldAddress: string;
  private _account?: Account;
  goldMinter: GoldMinterCalls;
  goldMinterAddress: string;
  character: CharacterCalls;
  characterAddress: string;
  settings: SettingsCalls;
  settingsAddress: string;
  resources: ResourcesCalls;
  resourcesAddress: string;
  characterMinter: CharacterMinterCalls;
  characterMinterAddress: string;

  constructor(params: InitialParams) {
    if ('manifest' in params) {
      const config = createManifestFromJson(params.manifest);
      this.rpcUrl = config.world.metadata.rpc_url;
      this.worldAddress = config.world.address;

      const goldMinterAddress = config.contracts.find(
        (contract) =>
          contract.name === 'dojo_starter::systems::goldMinter::goldMinter'
      )?.address;

      if (!goldMinterAddress) {
        throw new Error('No goldMinter contract found in the manifest');
      }

      this.goldMinterAddress = goldMinterAddress;
      const characterAddress = config.contracts.find(
        (contract) =>
          contract.name === 'dojo_starter::systems::character::character'
      )?.address;

      if (!characterAddress) {
        throw new Error('No character contract found in the manifest');
      }

      this.characterAddress = characterAddress;
      const settingsAddress = config.contracts.find(
        (contract) =>
          contract.name === 'dojo_starter::systems::settings::settings'
      )?.address;

      if (!settingsAddress) {
        throw new Error('No settings contract found in the manifest');
      }

      this.settingsAddress = settingsAddress;
      const resourcesAddress = config.contracts.find(
        (contract) =>
          contract.name === 'dojo_starter::systems::resources::resources'
      )?.address;

      if (!resourcesAddress) {
        throw new Error('No resources contract found in the manifest');
      }

      this.resourcesAddress = resourcesAddress;
      const characterMinterAddress = config.contracts.find(
        (contract) =>
          contract.name ===
          'dojo_starter::systems::characterMinter::characterMinter'
      )?.address;

      if (!characterMinterAddress) {
        throw new Error('No characterMinter contract found in the manifest');
      }

      this.characterMinterAddress = characterMinterAddress;
    } else {
      this.rpcUrl = params.rpcUrl || LOCAL_KATANA;
      this.worldAddress = params.worldAddress;
      this.goldMinterAddress = params.goldMinterAddress;
      this.characterAddress = params.characterAddress;
      this.settingsAddress = params.settingsAddress;
      this.resourcesAddress = params.resourcesAddress;
      this.characterMinterAddress = params.characterMinterAddress;
    }
    this.toriiUrl = params.toriiUrl || LOCAL_TORII;
    this.relayUrl = params.relayUrl || LOCAL_RELAY;
    this._account = params.account;
    this.goldMinter = new GoldMinterCalls(
      this.goldMinterAddress,
      this._account
    );
    this.character = new CharacterCalls(this.characterAddress, this._account);
    this.settings = new SettingsCalls(this.settingsAddress, this._account);
    this.resources = new ResourcesCalls(this.resourcesAddress, this._account);
    this.characterMinter = new CharacterMinterCalls(
      this.characterMinterAddress,
      this._account
    );

    this.toriiPromise = createClient([], {
      rpcUrl: this.rpcUrl,
      toriiUrl: this.toriiUrl,
      worldAddress: this.worldAddress,
      relayUrl: this.relayUrl,
    });
  }

  get account(): Account | undefined {
    return this._account;
  }

  set account(account: Account) {
    this._account = account;
    this.goldMinter = new GoldMinterCalls(
      this.goldMinterAddress,
      this._account
    );
    this.character = new CharacterCalls(this.characterAddress, this._account);
    this.settings = new SettingsCalls(this.settingsAddress, this._account);
    this.resources = new ResourcesCalls(this.resourcesAddress, this._account);
    this.characterMinter = new CharacterMinterCalls(
      this.characterMinterAddress,
      this._account
    );
  }

  async query<T extends Query>(query: T, limit = 10, offset = 0) {
    const torii = await this.toriiPromise;

    return {
      torii,
      findEntities: async () => this.findEntities(query, limit, offset),
    };
  }

  async findEntities<T extends Query>(query: T, limit = 10, offset = 0) {
    const torii = await this.toriiPromise;

    const clause = convertQueryToToriiClause(query);

    const toriiResult = await torii.getEntities({
      limit,
      offset,
      clause,
    });

    return toriiResult as Record<string, QueryResult<T>>;
  }

  async findEntity<T extends Query>(query: T) {
    const result = await this.findEntities(query, 1);

    if (Object.values(result).length === 0) {
      return undefined;
    }

    return Object.values(result)[0] as QueryResult<T>;
  }
}
