kind = "DojoModel"
class_hash = "0x14562e8e15e1d82680bbbbdfdc0f154027dfec666e1431b07a23e48190f721c"
original_class_hash = "0x14562e8e15e1d82680bbbbdfdc0f154027dfec666e1431b07a23e48190f721c"
abi = "manifests/sepolia/base/abis/models/zidle4-TokenConfig-23178dee.json"
tag = "zidle4-TokenConfig"
qualified_path = "zidle::models::token_config::token_config"
manifest_name = "zidle4-TokenConfig-23178dee"

[[members]]
name = "token_address"
type = "ContractAddress"
key = true

[[members]]
name = "max_supply"
type = "u256"
key = false

[[members]]
name = "minted_count"
type = "u256"
key = false

[[members]]
name = "max_per_wallet"
type = "u256"
key = false

[[members]]
name = "is_open"
type = "bool"
key = false
