kind = "DojoModel"
class_hash = "0x14004dc44001a986a50787224f5a9a5e4cf71b19822b038949b80205353235d"
original_class_hash = "0x14004dc44001a986a50787224f5a9a5e4cf71b19822b038949b80205353235d"
abi = "manifests/dev/base/abis/models/zidle-Character-b1c9c790.json"
tag = "zidle-Character"
qualified_path = "zidle::models::character::character"
manifest_name = "zidle-Character-b1c9c790"

[[members]]
name = "token_id"
type = "u128"
key = true

[[members]]
name = "name"
type = "felt252"
key = false
