kind = "DojoModel"
class_hash = "0x1d80b88912fba8df0d0d1863914bf30a643a0bd114b28bb7837796b7f87e387"
original_class_hash = "0x1d80b88912fba8df0d0d1863914bf30a643a0bd114b28bb7837796b7f87e387"
abi = "manifests/dev/base/abis/models/zIdle-Player-46d20110.json"
tag = "zIdle-Player"
manifest_name = "zIdle-Player-46d20110"

[[members]]
name = "id"
type = "felt252"
key = true

[[members]]
name = "name"
type = "felt252"
key = false
