kind = "DojoModel"
class_hash = "0x51a8c5fccb48d29d595997e571366e92c5cd50387cf94e1845202c41e269e3"
original_class_hash = "0x51a8c5fccb48d29d595997e571366e92c5cd50387cf94e1845202c41e269e3"
abi = "manifests/dev/base/abis/models/zidle-Player-456cce7d.json"
tag = "zidle-Player"
qualified_path = "zidle::models::player::player"
manifest_name = "zidle-Player-456cce7d"

[[members]]
name = "id"
type = "felt252"
key = true

[[members]]
name = "name"
type = "felt252"
key = false
