kind = "DojoModel"
class_hash = "0x1d8559f7857feb01f7dea680dfd197c831003ec782c343b16af7d1defe119ed"
original_class_hash = "0x1d8559f7857feb01f7dea680dfd197c831003ec782c343b16af7d1defe119ed"
abi = "manifests/dev/base/abis/models/zIdle-Resource-5271b5ab.json"
tag = "zIdle-Resource"
manifest_name = "zIdle-Resource-5271b5ab"

[[members]]
name = "id"
type = "felt252"
key = true

[[members]]
name = "resource_type"
type = "u8"
key = true

[[members]]
name = "xp"
type = "u32"
key = false

[[members]]
name = "timestamp"
type = "felt252"
key = false

[[members]]
name = "subresource_type"
type = "u8"
key = false
