kind = "DojoModel"
class_hash = "0x7cf3722e0f0725453210c412eaf348e60eae1890ecb5b340b2a88cb6d8cc447"
original_class_hash = "0x7cf3722e0f0725453210c412eaf348e60eae1890ecb5b340b2a88cb6d8cc447"
abi = "manifests/dev/base/abis/models/zidle-Char-29c4e0a3.json"
tag = "zidle-Char"
qualified_path = "zidle::models::char::char"
manifest_name = "zidle-Char-29c4e0a3"

[[members]]
name = "token_id"
type = "u128"
key = true

[[members]]
name = "name"
type = "felt252"
key = false
