[world]
name = "zIdle"
description = "Idle RPG fully onchain."
# cover_uri = "file://assets/cover.png"
# icon_uri = "file://assets/icon.png"
website = "https://github.com/dojoengine/dojo-starter"
seed = "zIdle"

[world.socials]
x = "https://x.com/ohayo_dojo"
discord = "https://discord.gg/FB2wR6uF"
github = "https://github.com/dojoengine/dojo-starter"
telegram = "https://t.me/dojoengine"

[namespace]
default = "zIdle"

[env]
rpc_url = "https://starknet-sepolia.public.blastapi.io/rpc/v0_6"
account_address = "0x063fd4be5b4df3068e3c4ae4062e999609b96a569e69628d6ba3331bf56e826c"
private_key = "0x05c38e8a5fe551d71755d7c4c77ea8aa7083479b222b413fef3772205fefec00"