[package]
name = "zidle"
cairo-version = "=2.8.4"
version = "0.1.0"

[cairo]
sierra-replace-ids = true

[scripts]
dev = "sozo --profile dev clean && sozo --profile dev build && sozo --profile dev migrate apply"
slot = "sozo --profile slot clean && sozo --profile slot build && sozo --profile slot migrate apply"
slotdev = "sozo --profile slotdev clean && sozo --profile slotdev build && sozo --profile slotdev migrate apply"
sepolia = "sozo --profile sepolia clean && sozo --profile sepolia build && sozo --profile sepolia migrate apply -vvv"

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.0.10" }

[[target.starknet-contract]]
build-external-contracts = [
    "dojo::world::world_contract::world",
]

# Custom profiles
[profile.slot]
[profile.slotdev]
[profile.sepolia]