kind = "DojoModel"
class_hash = "0x78f9892bd89a70b23a04dce2bfcfe99a721beb1aa2c5d4b3669710addcccfc4"
original_class_hash = "0x78f9892bd89a70b23a04dce2bfcfe99a721beb1aa2c5d4b3669710addcccfc4"
abi = "manifests/slot/base/abis/models/zidle-TokenConfig-6e5e38c0.json"
tag = "zidle-TokenConfig"
qualified_path = "zidle::models::token_config::token_config"
manifest_name = "zidle-TokenConfig-6e5e38c0"

[[members]]
name = "token_address"
type = "ContractAddress"
key = true

[[members]]
name = "max_supply"
type = "u256"
key = false

[[members]]
name = "minted_count"
type = "u256"
key = false

[[members]]
name = "max_per_wallet"
type = "u256"
key = false

[[members]]
name = "is_open"
type = "bool"
key = false
