kind = "DojoModel"
class_hash = "0x4d7c7f6b335266ad573aff1edf01f7b2f1aff312a39d0bebc011f3b2ca92485"
original_class_hash = "0x4d7c7f6b335266ad573aff1edf01f7b2f1aff312a39d0bebc011f3b2ca92485"
abi = "manifests/slot/base/abis/models/zidle-Char-29c4e0a3.json"
tag = "zidle-Char"
qualified_path = "zidle::models::char::char"
manifest_name = "zidle-Char-29c4e0a3"

[[members]]
name = "id"
type = "felt252"
key = true

[[members]]
name = "token_id"
type = "u128"
key = true

[[members]]
name = "name"
type = "felt252"
key = false
