kind = "DojoContract"
class_hash = "0x16bd4d267c5e61561edfa4d7dee7a3d7c4dbacb0731e5619363e788ceecc25"
original_class_hash = "0x16bd4d267c5e61561edfa4d7dee7a3d7c4dbacb0731e5619363e788ceecc25"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/zidle-account-60aa04fd.json"
reads = []
writes = []
init_calldata = []
tag = "zidle-account"
systems = [
    "create",
    "rename",
]
manifest_name = "zidle-account-60aa04fd"
