kind = "DojoContract"
class_hash = "0x61bb415b503b51f8c2e1423fb78385ac86c95564837d11409621ee5b7158870"
original_class_hash = "0x61bb415b503b51f8c2e1423fb78385ac86c95564837d11409621ee5b7158870"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/zidle-character-3dec6fe1.json"
reads = []
writes = []
init_calldata = []
tag = "zidle-character"
systems = ["create"]
manifest_name = "zidle-character-3dec6fe1"
