kind = "DojoContract"
class_hash = "0x43fab6c5d10772cacfaced810b16aea97a921550c90ec3682b79134712584db"
original_class_hash = "0x43fab6c5d10772cacfaced810b16aea97a921550c90ec3682b79134712584db"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/zidle-account-60aa04fd.json"
reads = []
writes = []
init_calldata = []
tag = "zidle-account"
systems = [
    "create",
    "rename",
]
manifest_name = "zidle-account-60aa04fd"
