kind = "DojoContract"
class_hash = "0x4816157f38a3cae8204651c0d1a2271e87dea34fa6e8f4b62f2505a6448eadc"
original_class_hash = "0x4816157f38a3cae8204651c0d1a2271e87dea34fa6e8f4b62f2505a6448eadc"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/zIdle-account-63d21c71.json"
reads = []
writes = []
init_calldata = []
tag = "zIdle-account"
manifest_name = "zIdle-account-63d21c71"
