kind = "DojoContract"
class_hash = "0x6c49b71fe374a86ae84359acc8d08a36e5a26611f785e842ced819d707d7442"
original_class_hash = "0x6c49b71fe374a86ae84359acc8d08a36e5a26611f785e842ced819d707d7442"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/zidle-character-3dec6fe1.json"
reads = []
writes = []
init_calldata = []
tag = "zidle-character"
systems = ["create"]
manifest_name = "zidle-character-3dec6fe1"
