kind = "DojoContract"
class_hash = "0x51d4c632a6b1d86e2fd403576f59a39bf598cff1783ac45913dc04b6cdfe39d"
original_class_hash = "0x51d4c632a6b1d86e2fd403576f59a39bf598cff1783ac45913dc04b6cdfe39d"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/zidle-resources-14ead52a.json"
reads = []
writes = []
init_calldata = []
tag = "zidle-resources"
systems = [
    "mine",
    "harvest",
    "sell",
]
manifest_name = "zidle-resources-14ead52a"
