kind = "DojoContract"
class_hash = "0xe4135b3e2e7778d5ac3b472b5cdbf50aefcf1fd2867a7754edaf62c9b7b5fc"
original_class_hash = "0xe4135b3e2e7778d5ac3b472b5cdbf50aefcf1fd2867a7754edaf62c9b7b5fc"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/zidle-character_minter-65ab56f7.json"
reads = []
writes = []
init_calldata = []
tag = "zidle-character_minter"
systems = ["set_open"]
manifest_name = "zidle-character_minter-65ab56f7"
