kind = "DojoContract"
class_hash = "0x1aa0129f01e73e7a9fd4618635cb67cf153d3561700ec9370581af28f7702fd"
original_class_hash = "0x1aa0129f01e73e7a9fd4618635cb67cf153d3561700ec9370581af28f7702fd"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/zidle-character_token-219118e6.json"
reads = []
writes = []
init_calldata = []
tag = "zidle-character_token"
systems = [
    "mint",
    "burn",
]
manifest_name = "zidle-character_token-219118e6"
