kind = "DojoContract"
class_hash = "0x435085c73d56964658a5b75e2346f31da293c1f9905e77b00aaa651c969ff7d"
original_class_hash = "0x435085c73d56964658a5b75e2346f31da293c1f9905e77b00aaa651c969ff7d"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/zidle-resources-14ead52a.json"
reads = []
writes = []
init_calldata = []
tag = "zidle-resources"
systems = [
    "mine",
    "harvest",
    "sell",
]
manifest_name = "zidle-resources-14ead52a"
